export const WIDGET_FORM_READY = "WIDGET_FORM_READY";
export const WIDGET_FORM_MOUNT = "WIDGET_FORM_MOUNT";
export const WIDGET_FORM_SUCCESS = "WIDGET_FORM_SUCCESS";
export const WIDGET_FORM_CLOSE = "WIDGET_FORM_CLOSE";
